apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mystorageclass
  hostPath:
    path: "/v1"

thêm thêm 

khong them gi ca 

thich them thi sao
